name: Extract and Print Test Case IDs

on:
  workflow_dispatch:

jobs:
  extract-ids:
    runs-on: ubuntu-latest
    outputs:
      ids: ${{ steps.extract.outputs.ids }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read testcases.json and extract IDs
        id: extract
        run: |
          # Extract IDs from the JSON file using jq
          ids=$(jq -r '[.preOrderFunctional[].id | tonumber] | join(",")' testcases.json)
          # Set the output for the job
          echo "ids=[$ids]" >> $GITHUB_OUTPUT

  print-ids:
    runs-on: ubuntu-latest
    needs: extract-ids
    steps:
      - name: Print extracted IDs
        run: | 
          echo "Extracted IDs: ${{ needs.extract-ids.outputs.ids }}"
  up-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: Report
          path: ./testfolder
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
  performance_testing_all:
    name: All
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testID: [1,2,3]
      max-parallel: 0
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
      
      - name: Wait before starting test
        run: sleep 2 
