## Workflow for building and deploying into SAP Commerce cloud CCV2 dev 
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  BUILD_NAME:  D1.BUILD.$(date +'%Y.%m.%d.%H.%M')
  DATABASE_UPDATE_MODE: UPDATE
  DEPLOYMENT_STRATEGY: ROLLING_UPDATE
  ENVIRONMENT_CODE: d1
name: 'DEVELOP BUILD'
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      buildStep:
        description: 'Build/Deploy:'
        required: true
        default: 'deploy'
        type: choice
        options:
          - build
          - deploy
      buildNo:
        description: 'Build No:'
        required: false
        type: string
      platformUpdate:
        description: 'Select when Build Step is Deploy. Platform Update: NONE (No Migration), UPDATE (Migration)'
        required: false
        default: 'UPDATE'
        type: choice
        options:
          - UPDATE
          - NONE
      deploymentMode:
        description: 'Select Deployment Mode when Build Step is Deploy'
        required: false
        default: 'ROLLING_UPDATE'
        type: choice
        options:
          - ROLLING_UPDATE
          - RECREATE    
      failstep:
        description: 'Fail deployment True/false'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'            
jobs:
  VALIDATION:
    name: VALIDATION
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context   
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: echo "$GITHUB_CONTEXT"
        shell: bash    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: DateTime
        run: |
          current_time=$(TZ="America/Chicago" date +"%Y-%m-%d %H:%M:%S CST")
           current_time_ist=$(TZ="Asia/Kolkata" date +"%Y-%m-%d %H:%M:%S IST")
          echo "current_time CST= $current_time"
          echo "current_time IST = $current_time_ist"
          echo "{date}={$(date)}"          
      - name: Send notification to Microsoft Teams (Start)
        run: |
           current_time=$(TZ="America/Chicago" date +"%Y-%m-%d %H:%M:%S CST")
           curl -X POST -H "Content-Type: application/json" --data '{
            "text": "Time: $current_time <br>Trigger By: ${{github.actor}} <br>ENV:D1 <br><br> Validation is Started <br><br> Check out the HTML file in the artifacts of this run: https://github.com/sumitkharche/az-function-test/actions/runs/'${{github.run_id}}'"}' https://webhook-test.com/46fcde0069fc598bc1cf69b69778f3cf
              
      - name: INTEGRATION TESTING (MOCK)
        run: |
          echo "Run your integration tests(mock) here!"
      - name: Wait 5 sec
        run: sleep 5          
  SAPCOM_BUILD:
    if: ${{github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.buildStep == 'build')}}
    name: BUILD
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: VALIDATION
    steps:
      - name: Create Build
        run: |
          echo "URL: ${{env.BRANCH_NAME}}"         
  SAPCOM_DEPLOY:
    if: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.buildStep == 'deploy' && github.event.inputs.buildNo != ''}}
    name: DEPLOY
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:    
      - name: Send notification to Microsoft Teams (Start)
        run: |
           curl -X POST -H "Content-Type: application/json" --data '{
            "text": "Trigger By: ${{github.actor}} <br>ENV:D1 <br><br> Build is Started <br><br> Check out the HTML file in the artifacts of this run: https://github.com/sumitkharche/az-function-test/actions/runs/'${{github.run_id}}'"}' https://webhook-test.com/46fcde0069fc598bc1cf69b69778f3cf
    
      - name: Create Deployment
        run: |
         echo "URL: ${{env.BRANCH_NAME}}"
      - name: Wait 10 sec
        run: sleep 10
      # Add this step to intentionally fail the job
      - name: Simulate Failure (for testing)
        if: ${{github.event.inputs.failstep == 'true'}}
        run: exit 1  # This will fail the job intentionally        
      # Add a failure notification step here
      - name: Notify Teams on Deployment Failure
        if: ${{ success() }}  # Trigger this step only if the job fails
        run: |
          curl -X POST -H "Content-Type: application/json" --data '{
           "text": "ENV:D1 <br><br> Deployment Completed <br><br> Check out the HTML file in the artifacts of this run: https://github.com/sumitkharche/az-function-test/actions/runs/'${{github.run_id}}'"}' https://webhook-test.com/46fcde0069fc598bc1cf69b69778f3cf        
      
      - name: Notify Teams on Deployment Failure
        if: ${{ failure() }}  # Trigger this step only if the job fails
        run: |
          curl -X POST -H "Content-Type: application/json" --data '{
           "text": "ENV:D1 <br><br> Deployment FAILED <br><br> Check out the HTML file in the artifacts of this run: https://github.com/sumitkharche/az-function-test/actions/runs/'${{github.run_id}}'"}' https://webhook-test.com/46fcde0069fc598bc1cf69b69778f3cf        
  INTEGRATION_E2E:
    name: INTEGRATION TESTING (E2E)
    runs-on: ubuntu-latest
    needs: SAPCOM_DEPLOY
    steps:    
      - name: INTEGRATION TESTING (E2E)
        run: |
          echo "Run your integration tests(E2E) here!" 
  REGRESSION:
    name: REGRESSION TESTING
    runs-on: ubuntu-latest
    needs: INTEGRATION_E2E
    steps:    
      - name: REGRESSION TESTING (E2E)
        run: |
          echo "Run your REGRESSION tests(E2E) here!" 
