name: Test

on:
  workflow_dispatch:
    inputs:
      performanceTesting:
        description: 'Run Performance Tests:'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      runSpecific:
        description: 'Do you want to run specific test cases or all?'
        required: false
        type: choice
        default: 'all'
        options: 
          - 'all'
          - 'specific'
      specificTestCases:
        description: 'Enter specific test case IDs separated by commas (only used if "specific" is selected above)'
        required: false
jobs:
  Build_testcases_parameter:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.performanceTesting == 'true' && github.event.inputs.runSpecific == 'specific'}}
    name: Build parameter
    outputs:
      testIDs: ${{ steps.set_test_ids.outputs.testIDs }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
      - name: 'Determine Test IDs'
        id: set_test_ids
        run: |
          test_case_string="${{ github.event.inputs.specificTestCases }}"
          # Replace commas with JSON array format
          json_array=$(echo "$test_case_string" | sed 's/,/,/g' | sed 's/^/[ /; s/$/ ]/' | sed 's/ //g')
          echo "Formatted JSON array: $json_array" # Debugging output
          echo "testIDs=$json_array" >> "$GITHUB_OUTPUT"
  print_test_ids:
    name: Print Test IDs
    runs-on: ubuntu-latest
    needs: Build_testcases_parameter
    steps:
      - name: Print Test IDs11
        run: |
          echo "Test IDs from the previous job:"
          echo "${{ needs.Build_testcases_parameter.outputs.testIDs }}"
  performance_testing_specific:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.performanceTesting == 'true' && github.event.inputs.runSpecific == 'specific'}}
    name: Specific
    runs-on: ubuntu-latest
    needs: Build_testcases_parameter
    strategy:
      max-parallel: 1 # Ensures tests run sequentially
      matrix:
        testID: ${{fromJson(needs.Build_testcases_parameter.outputs.testIDs)}}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4         
      - name: Wait before starting test
        run: sleep 5 
        
  Build_testcases_parameter_all:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.performanceTesting == 'true' && github.event.inputs.runSpecific == 'all'}}
    name: Build parameter all
    outputs:
      ids: ${{ steps.extract.outputs.ids }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
      - name: Read testcases.json and extract IDs
        id: extract
        run: |
          # Extract IDs from the JSON file using jq
          ids=$(jq -r '[.performanceTests[].id | tonumber] | join(",")' testcases.json)
          # Set the output for the job
          echo "ids=[$ids]" >> $GITHUB_OUTPUT

  print_test_ids_all:
    name: Print Test IDs all
    runs-on: ubuntu-latest
    needs: Build_testcases_parameter_all
    steps:
      - name: Print Test IDs
        run: |
          echo "Extracted IDs: [${{ needs.Build_testcases_parameter_all.outputs.ids }}]"
  performance_testing_all:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.performanceTesting == 'true' && github.event.inputs.runSpecific == 'all'}}  
    name: All
    runs-on: ubuntu-latest
    needs: Build_testcases_parameter_all
    strategy:
      matrix:
        testID: ${{fromJson(needs.Build_testcases_parameter_all.outputs.ids)}}
      max-parallel: 1  # Still use this to attempt sequential execution
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
      
      - name: Wait before starting test
        run: sleep 10 
