name: Test

on:
  workflow_dispatch:
jobs:
  performance_testing:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testID: [1,2]
      max-parallel: 1  # Still use this to attempt sequential execution
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
      
      - name: Wait before starting test
        run: sleep 10 
