name: Test

on:
  workflow_dispatch:
    inputs:
      performanceTesting:
        description: 'Run Performance Tests:'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      runSpecific:
        description: 'Do you want to run specific test cases or all?'
        required: false
        type: choice
        default: 'all'
        options: 
          - 'all'
          - 'specific'
      specificTestCases:
        description: 'Enter specific test case IDs separated by commas (only used if "specific" is selected above)'
        required: false
jobs:
  Build_testcases_parameter:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.performanceTesting == 'true' && github.event.inputs.runSpecific == 'specific'}}
    name: Build parameter
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
      - name: 'Determine Test IDs'
        id: set_test_ids
        run: |
            # Convert the specificTestCases input to an array
            specificTestCases="${{ github.event.inputs.specificTestCases }}"
            cleaned_ids=$(echo $specificTestCases | tr -d '[] ')
            IFS=',' read -ra test_case_array <<< "$cleaned_ids"
            # Convert array to a comma-separated string
            testIDs=$(IFS=, ; echo "${test_case_array[*]}")
            echo "testIDs=$testIDs" >> $GITHUB_ENV
  performance_testing_specific:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.performanceTesting == 'true' && github.event.inputs.runSpecific == 'specific'}}
    name: Specific
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # Ensures tests run sequentially
      matrix:
        testID: ${{ fromJson(env.testIDs) }}    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4         
      - name: Wait before starting test
        run: sleep 5 

  performance_testing_all:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.performanceTesting == 'true' && github.event.inputs.runSpecific == 'all'}}  
    name: All
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testID: [1,2,3]
      max-parallel: 1  # Still use this to attempt sequential execution
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
      
      - name: Wait before starting test
        run: sleep 10 
